# Complete Guide to Pandas.

Hi All ✌️, writing an article on Kaggle after a very long time. 

In this one I try to cover all the basic **Pandas** operations. 

For this, I will use the Titanic dataset. I have added a few more data sources so that the kernel reaches the mass and also you can run it on those datasets without much change.

Hope you find it useful, and if you do, make sure to drop a 👍.

## Table of Contents(ToC):

#### 1. [The Basics](#content1)

#### 2. [Creating DataFrame](#content2)

#### 3. [Treating null values](#content3)

#### 4. [Modify/Add new column(s).](#content4)

#### 5. [Deleting columns](#content5)

#### 6. [Renaming columns](#content6)

#### 7.i. [Slicing DataFrame](#content7)

#### 7.ii. [Slicing using iloc and loc](#content8)

#### 8. [Adding a row](#content9)

#### 9. [Dropping row(s)](#content10)

#### 10. [Sorting](#content11)

#### 11. [Joins](#content12)

#### 12. [Groupby](#content13)

#### Importing modules.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

#### Importing data.

For this tutorial, we will use the standard Titanic Dataset.

In [2]:
train=pd.read_csv(r'C:\Users\Admin\Documents\Pandas\train.csv')
df=train.copy()

<a id="content1"></a>
## 1. The Basics

In [3]:
# See the first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# last 5 rows.
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
# n_samples x n_features
df.shape

(891, 12)

In [6]:
#List of all the columns
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
# Rows index
df.index

RangeIndex(start=0, stop=891, step=1)

In [8]:
# Values with their counts in a particular column
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [9]:
# General description of dataset.
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

<a id="content2"></a>
## 2. Creating DataFrame

In [10]:
# empty data frame
df_empty=pd.DataFrame()
df_empty.head()  #;)

Empty DataFrame
Columns: []
Index: []

In [11]:
# From dict
student_dict={'Name':['A','B','C'],'Age':[24,18,17],'Roll':[1,2,3]}
df_student=pd.DataFrame(student_dict).reset_index(drop=True) # without this adds an additional index column in df
df_student.head()

  Name  Age  Roll
0    A   24     1
1    B   18     2
2    C   17     3

<a id="content3"></a>
## 3. Treating null values

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
# on whole df.
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
# on a particular column
df['Age'].isnull().sum()

np.int64(177)

#### Impute null values

In [15]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Age'].isnull().sum()

np.int64(0)

In [16]:
df['Sex'].fillna(df['Sex'].mode(),inplace=True)
df['Sex'].isnull().sum()

np.int64(0)

<a id="content4"></a>
## 4. Modify/Add new column(s).
Adding another column or modify a column.

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
df['Sex']=df['Sex'].map({"male":'0',"female":"1"})
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S

In [19]:
# Finding last name and first name from Name column.
df['last_name']=df['Name'].apply(lambda x: x.split(',')[0])
df['first_name']=df['Name'].apply(lambda x: ' '.join(x.split(',')[1:]))

In [20]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,first_name
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry

In [21]:
# Sets to 1 for men in 3rd class.
df['Third&Men']=df.apply(lambda row: int(row['Pclass']==3 and row['Sex']=="0"),axis=1)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,first_name,Third&Men
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1

##### Calling some custom function.

In [22]:
def findAgeGroup(age):
    if age<18:
        return 1
    elif age>=18 and age<40:
        return 2
    elif age>=40 and age<60:
        return 3
    else:
        return 4
df['Age_group']=df['Age'].apply(lambda x: findAgeGroup(x))
# Calling a custom function.

In [23]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,first_name,Third&Men,Age_group
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

<a id="content5"></a>
## 5. Deleting columns

In [24]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,first_name,Third&Men,Age_group
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

In [25]:
df=df.drop(['PassengerId'],axis=1)
#df=df.drop(['PassengerId'],axis=1,inplace=True)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,last_name,first_name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

<a id="content6"></a>
## 6. Renaming columns

In [26]:
# Lets try to rename some columns. 
df=df.rename(columns={'Sex':'Gender','Name':'Full Name','last_name':'Surname','first_name':'Name'})
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

Similarly, we can do for whichever column we want.

<a id="content7"></a>
## 7.i Slicing DataFrame

In [27]:
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

In [28]:
# All rows with pclass==3
df_third_class=df[df['Pclass']==3].reset_index(drop=True) # w/0 drop=True it actually adds a index column rather.
df_third_class.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.000000,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,3,"Heikkinen, Miss. Laina",1,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
2,0,3,"Allen, Mr. William Henry",0,35.000000,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2
3,0,3,"Moran, Mr. James",0,29.699118,0,0,330877,8.4583,NaN,Q,Moran,Mr. James,1,2
4,0,3,"Palsson, Master. Gosta Leonard",0,2.000000,3,1,349909,21.0750,NaN,S,Palsson,Master. Gosta Leonard,1,1

In [29]:
# Females with age > 60
df_aged=df[(df['Age']>60) & (df['Gender']=="1")]
df_aged.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
275,1,1,"Andrews, Miss. Kornelia Theodosia",1,63.0,1,0,13502,77.9583,D7,S,Andrews,Miss. Kornelia Theodosia,0,4
483,1,3,"Turkula, Mrs. (Hedwig)",1,63.0,0,0,4134,9.5875,NaN,S,Turkula,Mrs. (Hedwig),0,4
829,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",1,62.0,0,0,113572,80.0000,B28,NaN,Stone,Mrs. George Nelson (Martha Evelyn),0,4

**Note that all these three ladies were saved as they were senior citizen and women so they may have been given priority.**

In [30]:
# Selecting some columns.
df1=df[['Age','Pclass','Gender']]
df1.head()

    Age  Pclass Gender
0  22.0       3      0
1  38.0       1      1
2  26.0       3      1
3  35.0       1      1
4  35.0       3      0

In [31]:
# Select numerical columns only
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

df_num = df.select_dtypes(include=numerics)
df_num.head()

   Survived  Pclass   Age  SibSp  Parch     Fare  Third&Men  Age_group
0         0       3  22.0      1      0   7.2500          1          2
1         1       1  38.0      1      0  71.2833          0          2
2         1       3  26.0      0      0   7.9250          0          2
3         1       1  35.0      1      0  53.1000          0          2
4         0       3  35.0      0      0   8.0500          1          2

In [32]:
# categorical columns
df_cat=df.select_dtypes(include=['object'])
df_cat.head()

,Full Name,Gender,Ticket,Cabin,Embarked,Surname,Name
0,"Braund, Mr. Owen Harris",0,A/5 21171,NaN,S,Braund,Mr. Owen Harris
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,PC 17599,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,"Heikkinen, Miss. Laina",1,STON/O2. 3101282,NaN,S,Heikkinen,Miss. Laina
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,113803,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,"Allen, Mr. William Henry",0,373450,NaN,S,Allen,Mr. William Henry

<a id="content8"></a>
## 7.ii Slicing using iloc and loc

#### iloc

In [33]:
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

In [34]:
# First 100 rows & all columns
df_sub1=df.iloc[0:100,:]
df_sub1.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

In [35]:
#First 250 rows with a subset of columns

#df_sub2=df.iloc[:250,['Age']] 
# This will throw an error as iloc only consumes integres as indices.

df_sub2=df.iloc[:250,[1,8]] 
#Returns first 250 rows and columns at those indices in df.columns.
df_sub2.head()

   Pclass     Fare
0       3   7.2500
1       1  71.2833
2       3   7.9250
3       1  53.1000
4       3   8.0500

#### loc

In [36]:
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

In [37]:
# First 500 rows.
df_sub3=df.loc[:500,:]

In [38]:
# Gender and age of age >50
df_sub4=df.loc[(df['Age']>50),['Gender','Age']]
df_sub4.head()

   Gender   Age
6       0  54.0
11      1  58.0
15      1  55.0
33      0  66.0
54      0  65.0

<a id="content9"></a>
## 8. Adding a row

In [39]:
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,2
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0,2
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1,2

In [40]:
# Adding row using 'append' function
row=dict({'Age':24,'Full Name':'Peter','Survived':'Y'})
df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
# assumes Nan for absent keys(columns)
df.tail()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
887,1,1.0,"Graham, Miss. Margaret Edith",1,19.000000,0.0,0.0,112053,30.00,B42,S,Graham,Miss. Margaret Edith,0.0,2.0
888,0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1.0,2.0,W./C. 6607,23.45,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie""",0.0,2.0
889,1,1.0,"Behr, Mr. Karl Howell",0,26.000000,0.0,0.0,111369,30.00,C148,C,Behr,Mr. Karl Howell,0.0,2.0
890,0,3.0,"Dooley, Mr. Patrick",0,32.000000,0.0,0.0,370376,7.75,NaN,Q,Dooley,Mr. Patrick,1.0,2.0
891,Y,NaN,Peter,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# Adding new row using loc
df.loc[len(df.index)]=row
df.tail()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
888,0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1.0,2.0,W./C. 6607,23.45,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie""",0.0,2.0
889,1,1.0,"Behr, Mr. Karl Howell",0,26.000000,0.0,0.0,111369,30.00,C148,C,Behr,Mr. Karl Howell,0.0,2.0
890,0,3.0,"Dooley, Mr. Patrick",0,32.000000,0.0,0.0,370376,7.75,NaN,Q,Dooley,Mr. Patrick,1.0,2.0
891,Y,NaN,Peter,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,Y,NaN,Peter,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
df.tail()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
888,0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1.0,2.0,W./C. 6607,23.45,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie""",0.0,2.0
889,1,1.0,"Behr, Mr. Karl Howell",0,26.000000,0.0,0.0,111369,30.00,C148,C,Behr,Mr. Karl Howell,0.0,2.0
890,0,3.0,"Dooley, Mr. Patrick",0,32.000000,0.0,0.0,370376,7.75,NaN,Q,Dooley,Mr. Patrick,1.0,2.0
891,Y,NaN,Peter,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,Y,NaN,Peter,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<a id="content10"></a>
## 9. Dropping row(s)

In [43]:
df=df.drop(df.index[-1],axis=0) # Deletes last row
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3.0,"Braund, Mr. Owen Harris",0,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1.0,2.0
1,1,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1.0,0.0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0.0,2.0
2,1,3.0,"Heikkinen, Miss. Laina",1,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0.0,2.0
3,1,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1.0,0.0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0.0,2.0
4,0,3.0,"Allen, Mr. William Henry",0,35.0,0.0,0.0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1.0,2.0

In [44]:
df.tail()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
887,1,1.0,"Graham, Miss. Margaret Edith",1,19.000000,0.0,0.0,112053,30.00,B42,S,Graham,Miss. Margaret Edith,0.0,2.0
888,0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",1,29.699118,1.0,2.0,W./C. 6607,23.45,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie""",0.0,2.0
889,1,1.0,"Behr, Mr. Karl Howell",0,26.000000,0.0,0.0,111369,30.00,C148,C,Behr,Mr. Karl Howell,0.0,2.0
890,0,3.0,"Dooley, Mr. Patrick",0,32.000000,0.0,0.0,370376,7.75,NaN,Q,Dooley,Mr. Patrick,1.0,2.0
891,Y,NaN,Peter,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<a id="content11"></a>
## 10. Sorting

In [45]:
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
0,0,3.0,"Braund, Mr. Owen Harris",0,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,1.0,2.0
1,1,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1.0,0.0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0.0,2.0
2,1,3.0,"Heikkinen, Miss. Laina",1,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,0.0,2.0
3,1,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1.0,0.0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),0.0,2.0
4,0,3.0,"Allen, Mr. William Henry",0,35.0,0.0,0.0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1.0,2.0

In [46]:
# sorting by age say in decreasing order.
df=df.sort_values(by=['Age'],ascending=False) # can specify multiple columns in a list as well.
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
630,1,1.0,"Barkworth, Mr. Algernon Henry Wilson",0,80.0,0.0,0.0,27042,30.0000,A23,S,Barkworth,Mr. Algernon Henry Wilson,0.0,4.0
851,0,3.0,"Svensson, Mr. Johan",0,74.0,0.0,0.0,347060,7.7750,NaN,S,Svensson,Mr. Johan,1.0,4.0
96,0,1.0,"Goldschmidt, Mr. George B",0,71.0,0.0,0.0,PC 17754,34.6542,A5,C,Goldschmidt,Mr. George B,0.0,4.0
493,0,1.0,"Artagaveytia, Mr. Ramon",0,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr. Ramon,0.0,4.0
116,0,3.0,"Connors, Mr. Patrick",0,70.5,0.0,0.0,370369,7.7500,NaN,Q,Connors,Mr. Patrick,1.0,4.0

<a id="content12"></a>
## 11. Joins

Let's create two separate data frames and try all 5 (Cross,Inner, Left, Right,and Outer Joins).

In [47]:
sno=[i+1 for i in range(100)]
marks=np.random.randint(100,size=100)
print(len(marks))
marks_df=pd.DataFrame({'Sno':sno,'Marks':marks})
marks_df.head()

100

   Sno  Marks
0    1     79
1    2     55
2    3     82
3    4     83
4    5     61

In [48]:
sno=[i+1 for i in range(100)]
age=np.random.randint(100,size=100)
print(len(marks))
age_df=pd.DataFrame({'Sno':sno,'Age':age})
age_df.head()

100

   Sno  Age
0    1   41
1    2   43
2    3   83
3    4   72
4    5   94

#### Cross join

In [49]:
cross_join=pd.merge(marks_df,age_df,how='cross')
print(cross_join.shape)
cross_join.head()

(10000, 4)

   Sno_x  Marks  Sno_y  Age
0      1     79      1   41
1      1     79      2   43
2      1     79      3   83
3      1     79      4   72
4      1     79      5   94

#### Inner Join

In [50]:
inner_join=pd.merge(age_df,marks_df,how='inner',on='Sno') # 'how' defaults to 'inner' only.
print(inner_join.shape)
inner_join.head()

(100, 3)

   Sno  Age  Marks
0    1   41     79
1    2   43     55
2    3   83     82
3    4   72     83
4    5   94     61

#### Left and Right Outer Join(s)

Lets add some more rows to either frame so that left and right outer join makes sense

In [51]:
age_df.loc[len(age_df.index)]={'Sno':101,'Age':23}
age_df.loc[len(age_df.index)]={'Sno':102,'Age':27}
age_df.loc[len(age_df.index)]={'Sno':104,'Age':29}
age_df.loc[len(age_df.index)]={'Sno':103,'Age':32}
age_df.loc[len(age_df.index)]={'Sno':105,'Age':53}

In [52]:
#left join
left_join=pd.merge(age_df,marks_df,how='left',on='Sno')
print(left_join.shape)
left_join.tail()

(105, 3)

     Sno  Age  Marks
100  101   23    NaN
101  102   27    NaN
102  104   29    NaN
103  103   32    NaN
104  105   53    NaN

 **Marks=Nan** confirms the left join.

In [53]:
#right join
right_join=pd.merge(marks_df,age_df,how='right',on='Sno')
print(right_join.shape)
right_join.tail()

(105, 3)

     Sno  Marks  Age
100  101    NaN   23
101  102    NaN   27
102  104    NaN   29
103  103    NaN   32
104  105    NaN   53

**Marks=Nan** confirms the right join in this case as the order of input frames is also reversed.

#### Full outer join
One last time, lets modify the marks frame also to test **Full outer join.**

In [54]:
marks_df.loc[len(marks_df.index)]={'Sno':106,'Marks':79}
marks_df.tail()

     Sno  Marks
96    97     76
97    98     78
98    99     72
99   100     17
100  106     79

In [55]:
#outer join
out_join=pd.merge(marks_df,age_df,how='outer',on='Sno')
print(out_join.shape)
out_join.tail(10)

(106, 3)

     Sno  Marks   Age
96    97   76.0  67.0
97    98   78.0  84.0
98    99   72.0  99.0
99   100   17.0  35.0
100  101    NaN  23.0
101  102    NaN  27.0
102  103    NaN  32.0
103  104    NaN  29.0
104  105    NaN  53.0
105  106   79.0   NaN

Row index **100** is added in putput which confirms the **full outer join**

<a id="content13"></a>
## 12. Groupby

Let's get back to our titanic dataset.

In [56]:
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
630,1,1.0,"Barkworth, Mr. Algernon Henry Wilson",0,80.0,0.0,0.0,27042,30.0000,A23,S,Barkworth,Mr. Algernon Henry Wilson,0.0,4.0
851,0,3.0,"Svensson, Mr. Johan",0,74.0,0.0,0.0,347060,7.7750,NaN,S,Svensson,Mr. Johan,1.0,4.0
96,0,1.0,"Goldschmidt, Mr. George B",0,71.0,0.0,0.0,PC 17754,34.6542,A5,C,Goldschmidt,Mr. George B,0.0,4.0
493,0,1.0,"Artagaveytia, Mr. Ramon",0,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr. Ramon,0.0,4.0
116,0,3.0,"Connors, Mr. Patrick",0,70.5,0.0,0.0,370369,7.7500,NaN,Q,Connors,Mr. Patrick,1.0,4.0

#### Before, we move onto Groupby in pandas, lets recollect groupby from SQL. A SQL query, may contain these parts (some might be optional like having etc...):


1. Table name (**from**)
2. Some condition to filter rows (**where clause**)
3. Attribute to groupby on (**groupby attributes**)
4. Filter rows after groupby (**having clause**)
5. Display attributes in the final result. (**select**)


##### Let's now see how to mimic this in Pandas ;)

In [57]:
df.head()

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
630,1,1.0,"Barkworth, Mr. Algernon Henry Wilson",0,80.0,0.0,0.0,27042,30.0000,A23,S,Barkworth,Mr. Algernon Henry Wilson,0.0,4.0
851,0,3.0,"Svensson, Mr. Johan",0,74.0,0.0,0.0,347060,7.7750,NaN,S,Svensson,Mr. Johan,1.0,4.0
96,0,1.0,"Goldschmidt, Mr. George B",0,71.0,0.0,0.0,PC 17754,34.6542,A5,C,Goldschmidt,Mr. George B,0.0,4.0
493,0,1.0,"Artagaveytia, Mr. Ramon",0,71.0,0.0,0.0,PC 17609,49.5042,NaN,C,Artagaveytia,Mr. Ramon,0.0,4.0
116,0,3.0,"Connors, Mr. Patrick",0,70.5,0.0,0.0,370369,7.7500,NaN,Q,Connors,Mr. Patrick,1.0,4.0

In [58]:
groups=df.groupby(['Pclass'])
# uncomment this: 
#groups.groups
groups.get_group(3) # Give some another no say 2 or 3 for its Pclass.

C:\Users\Admin\AppData\Local\Temp\ipykernel_20792\448852875.py:4: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  groups.get_group(3) # Give some another no say 2 or 3 for its Pclass.

,Survived,Pclass,Full Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Surname,Name,Third&Men,Age_group
851,0,3.0,"Svensson, Mr. Johan",0,74.00,0.0,0.0,347060,7.7750,NaN,S,Svensson,Mr. Johan,1.0,4.0
116,0,3.0,"Connors, Mr. Patrick",0,70.50,0.0,0.0,370369,7.7500,NaN,Q,Connors,Mr. Patrick,1.0,4.0
280,0,3.0,"Duane, Mr. Frank",0,65.00,0.0,0.0,336439,7.7500,NaN,Q,Duane,Mr. Frank,1.0,4.0
483,1,3.0,"Turkula, Mrs. (Hedwig)",1,63.00,0.0,0.0,4134,9.5875,NaN,S,Turkula,Mrs. (Hedwig),0.0,4.0
326,0,3.0,"Nysveen, Mr. Johan Hansen",0,61.00,0.0,0.0,345364,6.2375,NaN,S,Nysveen,Mr. Johan Hansen,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,1,3.0,"Nakid, Miss. Maria (""Mary"")",1,1.00,0.0,2.0,2653,15.7417,NaN,C,Nakid,"Miss. Maria (""Mary"")",0.0,1.0
164,0,3.0,"Panula, Master. Eino Viljami",0,1.00,4.0,1.0,3101295,39.6875,NaN,S,Panula,Master. Eino Viljami,1.0,1.0
469,1,3.0,"Baclini, Miss. Helene Barbara",1,0.75,2.0,1.0,2666,19.2583,NaN,C,Baclini,Miss. Helene Barbara,0.0,1.0
644,1,3.0,"Baclini, Miss. Eugenie",1,0.75,2.0,1.0,2666,19.2583,NaN,C,Baclini,Miss. Eugenie,0.0,1.0
803,1,3.0,"Thomas, Master. Assad Alexander",0,0.42,0.0,1.0,2625,8.5167,NaN,C,Thomas,Master. Assad Alexander,1.0,1.0

#### Average Age per Pclass

In [59]:
df_grp1=df.groupby(['Pclass'])
#df_grp1.head()

In [60]:
#Average Age per Pclass
df_grp1['Age'].mean()

Pclass
1.0    37.048118
2.0    29.866958
3.0    26.403259
Name: Age, dtype: float64

In [61]:
# Min/Max age per Pclass
df_grp1['Age'].min() #max()

Pclass
1.0    0.92
2.0    0.67
3.0    0.42
Name: Age, dtype: float64

In [62]:
# Count
df_grp1['Age'].count()

Pclass
1.0    216
2.0    184
3.0    491
Name: Age, dtype: int64

#### Using agg() function.
We can use the aggregate fucntion to aggregate results based on some column  or our custom condition

In [63]:
df=train.copy()
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [64]:
# Average per Pclass using 'agg' this time
df_grp2=df.groupby(['Pclass']).agg({'Age':lambda x: np.mean(x)}) 
df_grp2.head()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

In [65]:
# Min/Max,count,Sum for each Pclass usign agg function
df_grp3=df.groupby(['Pclass']).agg({'Age':'min'}).rename(columns={'Age':'Min Age'})
# Use 'max'/'sum' etc. for that operation. Note that this ignores 'nan' values.
df_grp3.head()

        Min Age
Pclass
1          0.92
2          0.67
3          0.42

In [66]:
# Names of all the pasengers in that class.
df_grp4=df.groupby(['Pclass']).agg({'Name':lambda x:', '.join(x)})
df_grp4.head()

                                                     Name
Pclass
1       Cumings, Mrs. John Bradley (Florence Briggs Th...
2       Nasser, Mrs. Nicholas (Adele Achem), Hewlett, ...
3       Braund, Mr. Owen Harris, Heikkinen, Miss. Lain...

In [67]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

##### Note one thing that we can use multile agg functions on a single attribute by providing list in value part.

In [68]:
df_grp5=df.groupby(['Pclass']).agg({'Age':['max','min']})
df_grp5.head() # Creates a MultiOndex Dataframe

         Age
         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

## Bonus: Iterating over rows in dataframe

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [70]:
for index,row in df.iterrows():
    # do something with row, say:
    print(row)
    pass

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object
PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object
PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object
PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object
PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object
PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object
PassengerId                          7
Survived                             0
Pclass                               1
Name           McCarthy, Mr. Timothy J
Sex                               male
Age                               54.0
SibSp                                0
Parch                                0
Ticket                           17463
Fare                           51.8625
Cabin                              E46
Embarked                             S
Name: 6, dtype: object
PassengerId                                 8
Survived                                    0
Pclass                                      3
Name           Palsson, Master. Gosta Leonard
Sex                                      male
Age                                       2.0
SibSp                                       3
Parch                                       1
Ticket                                 349909
Fare                                   21.075
Cabin                                     NaN
Embarked                                    S
Name: 7, dtype: object
PassengerId                                                    9
Survived                                                       1
Pclass                                                         3
Name           Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Sex                                                       female
Age                                                         27.0
SibSp                                                          0
Parch                                                          2
Ticket                                                    347742
Fare                                                     11.1333
Cabin                                                        NaN
Embarked                                                       S
Name: 8, dtype: object
PassengerId                                     10
Survived                                         1
Pclass                                           2
Name           Nasser, Mrs. Nicholas (Adele Achem)
Sex                                         female
Age                                           14.0
SibSp                                            1
Parch                                            0
Ticket                                      237736
Fare                                       30.0708
Cabin                                          NaN
Embarked                                         C
Name: 9, dtype: object
PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object
PassengerId                          12
Survived                              1
Pclass                                1
Name           Bonnell, Miss. Elizabeth
Sex                              female
Age                                58.0
SibSp                                 0
Parch                                 0
Ticket                           113783
Fare                              26.55
Cabin                              C103
Embarked                              S
Name: 11, dtype: object
PassengerId                                13
Survived                                    0
Pclass                                      3
Name           Saundercock, Mr. William Henry
Sex                                      male
Age                                      20.0
SibSp                                       0
Parch                                       0
Ticket                              A/5. 2151
Fare                                     8.05
Cabin                                     NaN
Embarked                                    S
Name: 12, dtype: object
PassengerId                             14
Survived                                 0
Pclass                                   3
Name           Andersson, Mr. Anders Johan
Sex                                   male
Age                                   39.0
SibSp                                    1
Parch                                    5
Ticket                              347082
Fare                                31.275
Cabin                                  NaN
Embarked                                 S
Name: 13, dtype: object
PassengerId                                      15
Survived                                          0
Pclass                                            3
Name           Vestrom, Miss. Hulda Amanda Adolfina
Sex                                          female
Age                                            14.0
SibSp                                             0
Parch                                             0
Ticket                                       350406
Fare                                         7.8542
Cabin                                           NaN
Embarked                                          S
Name: 14, dtype: object
PassengerId                                  16
Survived                                      1
Pclass                                        2
Name           Hewlett, Mrs. (Mary D Kingcome)
Sex                                      female
Age                                        55.0
SibSp                                         0
Parch                                         0
Ticket                                   248706
Fare                                       16.0
Cabin                                       NaN
Embarked                                      S
Name: 15, dtype: object
PassengerId                      17
Survived                          0
Pclass                            3
Name           Rice, Master. Eugene
Sex                            male
Age                             2.0
SibSp                             4
Parch                             1
Ticket                       382652
Fare                         29.125
Cabin                           NaN
Embarked                          Q
Name: 16, dtype: object
PassengerId                              18
Survived                                  1
Pclass                                    2
Name           Williams, Mr. Charles Eugene
Sex                                    male
Age                                     NaN
SibSp                                     0
Parch                                     0
Ticket                               244373
Fare                                   13.0
Cabin                                   NaN
Embarked                                  S
Name: 17, dtype: object
PassengerId                                                   19
Survived                                                       0
Pclass                                                         3
Name           Vander Planke, Mrs. Julius (Emelia Maria Vande...
Sex                                                       female
Age                                                         31.0
SibSp                                                          1
Parch                                                          0
Ticket                                                    345763
Fare                                                        18.0
Cabin                                                        NaN
Embarked                                                       S
Name: 18, dtype: object
PassengerId                         20
Survived                             1
Pclass                               3
Name           Masselmani, Mrs. Fatima
Sex                             female
Age                                NaN
SibSp                                0
Parch                                0
Ticket                            2649
Fare                             7.225
Cabin                              NaN
Embarked                             C
Name: 19, dtype: object
PassengerId                      21
Survived                          0
Pclass                            2
Name           Fynney, Mr. Joseph J
Sex                            male
Age                            35.0
SibSp                             0
Parch                             0
Ticket                       239865
Fare                           26.0
Cabin                           NaN
Embarked                          S
Name: 20, dtype: object
PassengerId                       22
Survived                           1
Pclass                             2
Name           Beesley, Mr. Lawrence
Sex                             male
Age                             34.0
SibSp                              0
Parch                              0
Ticket                        248698
Fare                            13.0
Cabin                            D56
Embarked                           S
Name: 21, dtype: object
PassengerId                             23
Survived                                 1
Pclass                                   3
Name           McGowan, Miss. Anna "Annie"
Sex                                 female
Age                                   15.0
SibSp                                    0
Parch                                    0
Ticket                              330923
Fare                                8.0292
Cabin                                  NaN
Embarked                                 Q
Name: 22, dtype: object
PassengerId                              24
Survived                                  1
Pclass                                    1
Name           Sloper, Mr. William Thompson
Sex                                    male
Age                                    28.0
SibSp                                     0
Parch                                     0
Ticket                               113788
Fare                                   35.5
Cabin                                    A6
Embarked                                  S
Name: 23, dtype: object
PassengerId                               25
Survived                                   0
Pclass                                     3
Name           Palsson, Miss. Torborg Danira
Sex                                   female
Age                                      8.0
SibSp                                      3
Parch                                      1
Ticket                                349909
Fare                                  21.075
Cabin                                    NaN
Embarked                                   S
Name: 24, dtype: object
PassengerId                                                   26
Survived                                                       1
Pclass                                                         3
Name           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          5
Ticket                                                    347077
Fare                                                     31.3875
Cabin                                                        NaN
Embarked                                                       S
Name: 25, dtype: object
PassengerId                         27
Survived                             0
Pclass                               3
Name           Emir, Mr. Farred Chehab
Sex                               male
Age                                NaN
SibSp                                0
Parch                                0
Ticket                            2631
Fare                             7.225
Cabin                              NaN
Embarked                             C
Name: 26, dtype: object
PassengerId                                28
Survived                                    0
Pclass                                      1
Name           Fortune, Mr. Charles Alexander
Sex                                      male
Age                                      19.0
SibSp                                       3
Parch                                       2
Ticket                                  19950
Fare                                    263.0
Cabin                             C23 C25 C27
Embarked                                    S
Name: 27, dtype: object
PassengerId                               29
Survived                                   1
Pclass                                     3
Name           O'Dwyer, Miss. Ellen "Nellie"
Sex                                   female
Age                                      NaN
SibSp                                      0
Parch                                      0
Ticket                                330959
Fare                                  7.8792
Cabin                                    NaN
Embarked                                   Q
Name: 28, dtype: object
PassengerId                     30
Survived                         0
Pclass                           3
Name           Todoroff, Mr. Lalio
Sex                           male
Age                            NaN
SibSp                            0
Parch                            0
Ticket                      349216
Fare                        7.8958
Cabin                          NaN
Embarked                         S
Name: 29, dtype: object
PassengerId                          31
Survived                              0
Pclass                                1
Name           Uruchurtu, Don. Manuel E
Sex                                male
Age                                40.0
SibSp                                 0
Parch                                 0
Ticket                         PC 17601
Fare                            27.7208
Cabin                               NaN
Embarked                              C
Name: 30, dtype: object
PassengerId                                                32
Survived                                                    1
Pclass                                                      1
Name           Spencer, Mrs. William Augustus (Marie Eugenie)
Sex                                                    female
Age                                                       NaN
SibSp                                                       1
Parch                                                       0
Ticket                                               PC 17569
Fare                                                 146.5208
Cabin                                                     B78
Embarked                                                    C
Name: 31, dtype: object
PassengerId                          33
Survived                              1
Pclass                                3
Name           Glynn, Miss. Mary Agatha
Sex                              female
Age                                 NaN
SibSp                                 0
Parch                                 0
Ticket                           335677
Fare                               7.75
Cabin                               NaN
Embarked                              Q
Name: 32, dtype: object
PassengerId                       34
Survived                           0
Pclass                             2
Name           Wheadon, Mr. Edward H
Sex                             male
Age                             66.0
SibSp                              0
Parch                              0
Ticket                    C.A. 24579
Fare                            10.5
Cabin                            NaN
Embarked                           S
Name: 33, dtype: object
PassengerId                         35
Survived                             0
Pclass                               1
Name           Meyer, Mr. Edgar Joseph
Sex                               male
Age                               28.0
SibSp                                1
Parch                                0
Ticket                        PC 17604
Fare                           82.1708
Cabin                              NaN
Embarked                             C
Name: 34, dtype: object
PassengerId                                36
Survived                                    0

##### Ideally for this we can use 'apply' method also as we saw in adding/modifying the column section.

#### Hope you found it useful, and if you did, make sure to drop a 👍.

#### Thanks, Bye!

## Link to other kernels in this series:

i. [Numpy: A Complete Guide to Numpy](https://www.kaggle.com/code/rajmehra03/a-complete-guide-to-numpy/) &

ii. [Python for DSA interviews.](https://www.kaggle.com/rajmehra03/python-for-dsa-interviews/)

## Rough

In [71]:
arr1=np.random.randint(100,size=(100,1))
arr2=np.random.randint(100,size=(100))
arr1

array([[47],
       [58],
       [50],
       [ 0],
       [88],
       [ 4],
       [ 3],
       [18],
       [15],
       [71],
       [ 2],
       [34],
       [21],
       [65],
       [62],
       [ 4],
       [23],
       [75],
       [97],
       [14],
       [ 9],
       [95],
       [86],
       [65],
       [47],
       [75],
       [ 6],
       [94],
       [47],
       [68],
       [84],
       [ 4],
       [36],
       [52],
       [52],
       [ 8],
       [68],
       [63],
       [67],
       [30],
       [19],
       [68],
       [45],
       [44],
       [83],
       [57],
       [87],
       [64],
       [68],
       [77],
       [49],
       [ 5],
       [47],
       [69],
       [11],
       [51],
       [63],
       [11],
       [53],
       [ 2],
       [33],
       [27],
       [90],
       [ 9],
       [90],
       [92],
       [18],
       [11],
       [78],
       [84],
       [41],
       [85],
       [83],
       [ 4],
       [66],
       [89],
       [27],
       [84],
       [93],
       [96],
       [85],
       [75],
       [ 4],
       [52],
       [43],
       [ 5],
       [56],
       [34],
       [ 4],
       [99],
       [98],
       [97],
       [58],
       [44],
       [28],
       [56],
       [ 4],
       [90],
       [63],
       [27]], dtype=int32)

In [72]:
arr2

array([40, 74, 52, 86, 90, 12, 86, 10,  9, 16, 67, 96, 27, 36, 28, 41, 50,
       56, 14, 35, 95, 93,  2, 16, 43, 73, 71, 85, 38, 58, 92, 13, 57, 13,
       51, 13, 12, 84, 96, 71, 87, 55, 29, 29, 92, 50, 46, 69, 56, 79, 33,
       18, 17, 59, 63, 25, 40, 13, 91, 44, 70, 64,  8, 98, 92, 10, 36, 64,
       71, 27, 15, 37, 21, 79, 63, 91, 97, 23, 74, 97, 74, 31, 12, 49, 72,
       36, 95,  5, 88, 41,  0, 73, 68, 79, 67, 17, 59, 84, 15, 74],
      dtype=int32)

#### Note the differnce in arr1 and arr2 above !